version: '3'
services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi:2.0
    ports:
      - 8090:8090
      - 8091:8091
  boundaryactor:
    image: boundarywalkeractor:2.0
    ##image: docker.io/lanluca/boundarywalkeractor:1.0
    depends_on:
      - wenv

## docker build -t steprobot:2.0 .
##it.unibo.kotlinSupports>docker-compose -f virtualrobotandstepper.yaml up